version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "Australia/Melbourne"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: ":arrow_up: "
    open-pull-requests-limit: 2