proxy:
  runtime: nodejs12.x
  handler: src/handlers/corsProxy.handler
  name: ${self:custom.shared.stackName}Handler
  memorySize: 128
  events:
    - httpApi:
        path: '/'
        method: '*'
        cors: true
